/**
 * One public-domain picture per subject — GENERATED. Do not hand-edit.
 *
 * Every entity that could be given a picture of ITSELF gets one here: the
 * Wikimedia Commons image for its Wikipedia article where that image is in the
 * public domain, and otherwise the first public-domain result of a Commons
 * search for the subject. Files live in public/art as ent-<entity-id>.jpg.
 *
 * PUBLIC DOMAIN ONLY, CHECKED PER FILE. Commons is full of CC BY-SA
 * photographs — of a statue, a building, a modern scholar — and those are not
 * period plates and not ours to print without credit. Each candidate's licence
 * metadata was read and anything that was not PD or CC0 was dropped, which is
 * why the coverage below is partial rather than total.
 *
 * Entities with no entry fall back to their section's plate pool, which is the
 * behaviour every book had before. Abstract ideas mostly land there.
 *
 * Regenerate by re-running the fetch; corrections belong in ENTITY_ART in
 * grimoireArt.ts, which is applied on top of the deal the same way.
 */

export const ENTITY_PLATES: Record<string, { plate: string; caption: string }> = {
  'abraham-abulafia': { plate: '/art/ent-abraham-abulafia.jpg', caption: 'Abraham Abulafia' },
  'abraham-von-franckenberg': { plate: '/art/ent-abraham-von-franckenberg.jpg', caption: 'Abraham von Franckenberg' },
  abraxas: { plate: '/art/ent-abraxas.jpg', caption: 'Abraxas' },
  'aby-warburg': { plate: '/art/ent-aby-warburg.jpg', caption: 'Aby Warburg' },
  'adam-kadmon': { plate: '/art/ent-adam-kadmon.jpg', caption: 'Adam Kadmon' },
  'adam-weishaupt': { plate: '/art/ent-adam-weishaupt.jpg', caption: 'Adam Weishaupt' },
  'agostino-steuco': { plate: '/art/ent-agostino-steuco.jpg', caption: 'Agostino Steuco' },
  'agrippa-de-vanitate': { plate: '/art/ent-agrippa-de-vanitate.jpg', caption: 'De Vanitate Scientiarum' },
  'ahiman-rezon': { plate: '/art/ent-ahiman-rezon.jpg', caption: 'Ahiman Rezon' },
  'al-razi': { plate: '/art/ent-al-razi.jpg', caption: 'Abū Bakr al-Rāzī' },
  'albert-mackey': { plate: '/art/ent-albert-mackey.jpg', caption: 'Albert G. Mackey' },
  'albert-pike': { plate: '/art/ent-albert-pike.jpg', caption: 'Albert Pike' },
  'albertus-magnus': { plate: '/art/ent-albertus-magnus.jpg', caption: 'Albertus Magnus' },
  alchemy: { plate: '/art/ent-alchemy.jpg', caption: 'Alchemy' },
  'aleister-crowley': { plate: '/art/ent-aleister-crowley.jpg', caption: 'Aleister Crowley' },
  'alex-owen': { plate: '/art/ent-alex-owen.jpg', caption: 'Alex Owen' },
  alexandria: { plate: '/art/ent-alexandria.jpg', caption: 'Alexandria' },
  alkahest: { plate: '/art/ent-alkahest.jpg', caption: 'The Alkahest' },
  'all-seeing-eye': { plate: '/art/ent-all-seeing-eye.jpg', caption: 'The All-Seeing Eye' },
  'allan-kardec': { plate: '/art/ent-allan-kardec.jpg', caption: 'Allan Kardec' },
  'amphitheatrum-sapientiae': { plate: '/art/ent-amphitheatrum-sapientiae.jpg', caption: 'Amphitheatrum Sapientiae Aeternae' },
  'andersons-constitutions': { plate: '/art/ent-andersons-constitutions.jpg', caption: 'Anderson’s Constitutions' },
  'andreas-libavius': { plate: '/art/ent-andreas-libavius.jpg', caption: 'Andreas Libavius' },
  'angelus-silesius': { plate: '/art/ent-angelus-silesius.jpg', caption: 'Angelus Silesius' },
  'anima-mundi': { plate: '/art/ent-anima-mundi.jpg', caption: 'Anima Mundi' },
  'animal-magnetism': { plate: '/art/ent-animal-magnetism.jpg', caption: 'Animal Magnetism' },
  'annie-besant': { plate: '/art/ent-annie-besant.jpg', caption: 'Annie Besant' },
  'anthony-sayer': { plate: '/art/ent-anthony-sayer.jpg', caption: 'Anthony Sayer' },
  anthroposophy: { plate: '/art/ent-anthroposophy.jpg', caption: 'Anthroposophy' },
  'antients-grand-lodge': { plate: '/art/ent-antients-grand-lodge.jpg', caption: 'The Antients Grand Lodge' },
  'antoine-faivre': { plate: '/art/ent-antoine-faivre.jpg', caption: 'Antoine Faivre' },
  'apollonius-of-tyana': { plate: '/art/ent-apollonius-of-tyana.jpg', caption: 'Apollonius of Tyana' },
  apuleius: { plate: '/art/ent-apuleius.jpg', caption: 'Apuleius of Madauros' },
  'arnald-of-villanova': { plate: '/art/ent-arnald-of-villanova.jpg', caption: 'Arnald of Villanova' },
  'art-of-memory-book': { plate: '/art/ent-art-of-memory-book.jpg', caption: 'The Art of Memory' },
  'art-of-memory': { plate: '/art/ent-art-of-memory.jpg', caption: 'The Art of Memory' },
  'arthur-edward-waite': { plate: '/art/ent-arthur-edward-waite.jpg', caption: 'A. E. Waite' },
  'as-above-so-below': { plate: '/art/ent-as-above-so-below.jpg', caption: 'As Above, So Below' },
  'astral-light': { plate: '/art/ent-astral-light.jpg', caption: 'The Astral Light' },
  'astral-projection': { plate: '/art/ent-astral-projection.jpg', caption: 'Astral Projection' },
  'atalanta-fugiens': { plate: '/art/ent-atalanta-fugiens.jpg', caption: 'Atalanta Fugiens' },
  'augustine-of-hippo': { plate: '/art/ent-augustine-of-hippo.jpg', caption: 'Augustine of Hippo' },
  'aurora-boehme': { plate: '/art/ent-aurora-boehme.jpg', caption: 'Aurora (Morgenröte im Aufgang)' },
  'aurora-consurgens': { plate: '/art/ent-aurora-consurgens.jpg', caption: 'Aurora Consurgens' },
  'austin-osman-spare': { plate: '/art/ent-austin-osman-spare.jpg', caption: 'Austin Osman Spare' },
  'automatic-writing': { plate: '/art/ent-automatic-writing.jpg', caption: 'Automatic Writing' },
  azoth: { plate: '/art/ent-azoth.jpg', caption: 'Azoth' },
  'azriel-of-gerona': { plate: '/art/ent-azriel-of-gerona.jpg', caption: 'Azriel of Gerona' },
  'baal-shem-tov': { plate: '/art/ent-baal-shem-tov.jpg', caption: 'The Baal Shem Tov' },
  baphomet: { plate: '/art/ent-baphomet.jpg', caption: 'Baphomet' },
  'basil-valentine': { plate: '/art/ent-basil-valentine.jpg', caption: 'Basil Valentine' },
  basilides: { plate: '/art/ent-basilides.jpg', caption: 'Basilides' },
  'benjamin-franklin': { plate: '/art/ent-benjamin-franklin.jpg', caption: 'Benjamin Franklin' },
  'book-of-the-law': { plate: '/art/ent-book-of-the-law.jpg', caption: 'The Book of the Law' },
  'bruno-execution': { plate: '/art/ent-bruno-execution.jpg', caption: 'The Execution of Giordano Bruno' },
  caduceus: { plate: '/art/ent-caduceus.jpg', caption: 'The Caduceus' },
  cagliostro: { plate: '/art/ent-cagliostro.jpg', caption: 'Count Cagliostro' },
  'carl-jung': { plate: '/art/ent-carl-jung.jpg', caption: 'C. G. Jung' },
  'chaldean-oracles': { plate: '/art/ent-chaldean-oracles.jpg', caption: 'The Chaldean Oracles' },
  'chevalier-ramsay': { plate: '/art/ent-chevalier-ramsay.jpg', caption: 'The Chevalier Ramsay' },
  'christian-cabala': { plate: '/art/ent-christian-cabala.jpg', caption: 'Christian Cabala' },
  'christian-rosenkreutz': { plate: '/art/ent-christian-rosenkreutz.jpg', caption: 'Christian Rosenkreutz' },
  'christian-theosophy': { plate: '/art/ent-christian-theosophy.jpg', caption: 'Christian Theosophy' },
  'christoph-besold': { plate: '/art/ent-christoph-besold.jpg', caption: 'Christoph Besold' },
  chrysopoeia: { plate: '/art/ent-chrysopoeia.jpg', caption: 'Chrysopoeia' },
  'chymical-wedding': { plate: '/art/ent-chymical-wedding.jpg', caption: 'The Chymical Wedding of Christian Rosenkreutz' },
  'cipher-manuscripts': { plate: '/art/ent-cipher-manuscripts.jpg', caption: 'The Cipher Manuscripts' },
  'city-of-the-sun': { plate: '/art/ent-city-of-the-sun.jpg', caption: 'The City of the Sun' },
  'cleopatra-alchemist': { plate: '/art/ent-cleopatra-alchemist.jpg', caption: 'Cleopatra the Alchemist' },
  comenius: { plate: '/art/ent-comenius.jpg', caption: 'Jan Amos Comenius' },
  'confessio-fraternitatis': { plate: '/art/ent-confessio-fraternitatis.jpg', caption: 'Confessio Fraternitatis' },
  'cornelius-agrippa': { plate: '/art/ent-cornelius-agrippa.jpg', caption: 'Heinrich Cornelius Agrippa' },
  'corpus-hermeticum': { plate: '/art/ent-corpus-hermeticum.jpg', caption: 'Corpus Hermeticum' },
  correspondences: { plate: '/art/ent-correspondences.jpg', caption: 'The Doctrine of Correspondences' },
  'cosimo-de-medici': { plate: '/art/ent-cosimo-de-medici.jpg', caption: 'Cosimo de’ Medici' },
  'count-saint-germain': { plate: '/art/ent-count-saint-germain.jpg', caption: 'The Count of Saint-Germain' },
  'crater-hermetis': { plate: '/art/ent-crater-hermetis.jpg', caption: 'Crater Hermetis' },
  'daniel-mogling': { plate: '/art/ent-daniel-mogling.jpg', caption: 'Daniel Mögling' },
  'de-arte-cabalistica': { plate: '/art/ent-de-arte-cabalistica.jpg', caption: 'De Arte Cabalistica' },
  'de-harmonia-mundi': { plate: '/art/ent-de-harmonia-mundi.jpg', caption: 'De Harmonia Mundi' },
  'de-praestigiis-daemonum': { plate: '/art/ent-de-praestigiis-daemonum.jpg', caption: 'De Praestigiis Daemonum' },
  'de-umbris-idearum': { plate: '/art/ent-de-umbris-idearum.jpg', caption: 'De Umbris Idearum' },
  'de-vita-libri-tres': { plate: '/art/ent-de-vita-libri-tres.jpg', caption: 'De Vita Libri Tres' },
  decknamen: { plate: '/art/ent-decknamen.jpg', caption: 'Decknamen' },
  demiurge: { plate: '/art/ent-demiurge.jpg', caption: 'The Demiurge' },
  devekut: { plate: '/art/ent-devekut.jpg', caption: 'Devekut' },
  'dion-fortune': { plate: '/art/ent-dion-fortune.jpg', caption: 'Dion Fortune' },
  disenchantment: { plate: '/art/ent-disenchantment.jpg', caption: 'Disenchantment' },
  'divine-sophia': { plate: '/art/ent-divine-sophia.jpg', caption: 'The Divine Sophia' },
  'doctrine-of-signatures': { plate: '/art/ent-doctrine-of-signatures.jpg', caption: 'The Doctrine of Signatures' },
  'dogme-et-rituel': { plate: '/art/ent-dogme-et-rituel.jpg', caption: 'Dogme et rituel de la haute magie' },
  'edward-kelley': { plate: '/art/ent-edward-kelley.jpg', caption: 'Edward Kelley' },
  'egil-asprem': { plate: '/art/ent-egil-asprem.jpg', caption: 'Egil Asprem' },
  'egyptian-rite': { plate: '/art/ent-egyptian-rite.jpg', caption: 'The Egyptian Rite' },
  'ein-sof': { plate: '/art/ent-ein-sof.jpg', caption: 'Ein Sof' },
  'eleazar-of-worms': { plate: '/art/ent-eleazar-of-worms.jpg', caption: 'Eleazar of Worms' },
  'elias-ashmole': { plate: '/art/ent-elias-ashmole.jpg', caption: 'Elias Ashmole' },
  'eliphas-levi': { plate: '/art/ent-eliphas-levi.jpg', caption: 'Éliphas Lévi' },
  'elixir-of-life': { plate: '/art/ent-elixir-of-life.jpg', caption: 'The Elixir of Life' },
  'ellic-howe': { plate: '/art/ent-ellic-howe.jpg', caption: 'Ellic Howe' },
  'emanuel-swedenborg': { plate: '/art/ent-emanuel-swedenborg.jpg', caption: 'Emanuel Swedenborg' },
  'emerald-tablet': { plate: '/art/ent-emerald-tablet.jpg', caption: 'The Emerald Tablet' },
  'enochian-language': { plate: '/art/ent-enochian-language.jpg', caption: 'The Enochian Language' },
  eranos: { plate: '/art/ent-eranos.jpg', caption: 'The Eranos Meetings' },
  'etz-hayyim': { plate: '/art/ent-etz-hayyim.jpg', caption: 'Etz Hayyim' },
  'expulsion-1492': { plate: '/art/ent-expulsion-1492.jpg', caption: 'The Expulsion from Spain' },
  'fama-fraternitatis': { plate: '/art/ent-fama-fraternitatis.jpg', caption: 'Fama Fraternitatis' },
  'faust-legend': { plate: '/art/ent-faust-legend.jpg', caption: 'The Faust Legend' },
  'ficino-translation': { plate: '/art/ent-ficino-translation.jpg', caption: 'Hermes Comes to Florence' },
  florence: { plate: '/art/ent-florence.jpg', caption: 'Florence' },
  'four-worlds': { plate: '/art/ent-four-worlds.jpg', caption: 'The Four Worlds' },
  'fox-sisters': { plate: '/art/ent-fox-sisters.jpg', caption: 'The Fox Sisters' },
  'frances-yates': { plate: '/art/ent-frances-yates.jpg', caption: 'Frances Yates' },
  'francesco-giorgi': { plate: '/art/ent-francesco-giorgi.jpg', caption: 'Francesco Giorgi' },
  'franz-anton-mesmer': { plate: '/art/ent-franz-anton-mesmer.jpg', caption: 'Franz Anton Mesmer' },
  'frederick-v': { plate: '/art/ent-frederick-v.jpg', caption: 'Frederick V of the Palatinate' },
  freemasonry: { plate: '/art/ent-freemasonry.jpg', caption: 'Freemasonry' },
  'friedrich-oetinger': { plate: '/art/ent-friedrich-oetinger.jpg', caption: 'Friedrich Christoph Oetinger' },
  'g-i-gurdjieff': { plate: '/art/ent-g-i-gurdjieff.jpg', caption: 'G. I. Gurdjieff' },
  gematria: { plate: '/art/ent-gematria.jpg', caption: 'Gematria' },
  'george-ripley': { plate: '/art/ent-george-ripley.jpg', caption: 'George Ripley' },
  'george-starkey': { plate: '/art/ent-george-starkey.jpg', caption: 'George Starkey' },
  'george-washington-cornerstone': { plate: '/art/ent-george-washington-cornerstone.jpg', caption: 'The Capitol Cornerstone Ceremony' },
  'george-washington': { plate: '/art/ent-george-washington.jpg', caption: 'George Washington' },
  'gerald-gardner': { plate: '/art/ent-gerald-gardner.jpg', caption: 'Gerald Gardner' },
  'gerona-circle': { plate: '/art/ent-gerona-circle.jpg', caption: 'The Gerona Circle' },
  'gershom-scholem': { plate: '/art/ent-gershom-scholem.jpg', caption: 'Gershom Scholem' },
  'giambattista-della-porta': { plate: '/art/ent-giambattista-della-porta.jpg', caption: 'Giambattista della Porta' },
  gilgul: { plate: '/art/ent-gilgul.jpg', caption: 'Gilgul' },
  'giordano-bruno': { plate: '/art/ent-giordano-bruno.jpg', caption: 'Giordano Bruno' },
  'girolamo-cardano': { plate: '/art/ent-girolamo-cardano.jpg', caption: 'Girolamo Cardano' },
  'giulio-camillo': { plate: '/art/ent-giulio-camillo.jpg', caption: 'Giulio Camillo' },
  gnosis: { plate: '/art/ent-gnosis.jpg', caption: 'Gnosis' },
  'gold-und-rosenkreuz': { plate: '/art/ent-gold-und-rosenkreuz.jpg', caption: 'The Gold- und Rosenkreuz' },
  'golden-dawn-schism': { plate: '/art/ent-golden-dawn-schism.jpg', caption: 'The Schism of 1900' },
  'golden-dawn': { plate: '/art/ent-golden-dawn.jpg', caption: 'The Hermetic Order of the Golden Dawn' },
  golem: { plate: '/art/ent-golem.jpg', caption: 'The Golem' },
  'grand-lodge-founding': { plate: '/art/ent-grand-lodge-founding.jpg', caption: 'The Founding of the Grand Lodge' },
  'grand-orient-de-france': { plate: '/art/ent-grand-orient-de-france.jpg', caption: 'The Grand Orient de France' },
  'greek-magical-papyri': { plate: '/art/ent-greek-magical-papyri.jpg', caption: 'The Greek Magical Papyri' },
  'green-lion': { plate: '/art/ent-green-lion.jpg', caption: 'The Green Lion' },
  'guillaume-postel': { plate: '/art/ent-guillaume-postel.jpg', caption: 'Guillaume Postel' },
  hasidism: { plate: '/art/ent-hasidism.jpg', caption: 'Hasidism' },
  'hayyim-vital': { plate: '/art/ent-hayyim-vital.jpg', caption: 'Hayyim Vital' },
  'heaven-and-hell': { plate: '/art/ent-heaven-and-hell.jpg', caption: 'Heaven and Hell' },
  heidelberg: { plate: '/art/ent-heidelberg.jpg', caption: 'Heidelberg' },
  heimarmene: { plate: '/art/ent-heimarmene.jpg', caption: 'Heimarmenē' },
  'heinrich-khunrath': { plate: '/art/ent-heinrich-khunrath.jpg', caption: 'Heinrich Khunrath' },
  'hekhalot-literature': { plate: '/art/ent-hekhalot-literature.jpg', caption: 'The Hekhalot Literature' },
  'helena-blavatsky': { plate: '/art/ent-helena-blavatsky.jpg', caption: 'Helena Petrovna Blavatsky' },
  'henry-corbin': { plate: '/art/ent-henry-corbin.jpg', caption: 'Henry Corbin' },
  'hermes-trismegistus': { plate: '/art/ent-hermes-trismegistus.jpg', caption: 'Hermes Trismegistus' },
  'hermetic-rebirth': { plate: '/art/ent-hermetic-rebirth.jpg', caption: 'Hermetic Rebirth' },
  hermeticism: { plate: '/art/ent-hermeticism.jpg', caption: 'Hermeticism' },
  hermopolis: { plate: '/art/ent-hermopolis.jpg', caption: 'Hermopolis' },
  'hilma-af-klint': { plate: '/art/ent-hilma-af-klint.jpg', caption: 'Hilma af Klint' },
  'hiram-abiff': { plate: '/art/ent-hiram-abiff.jpg', caption: 'Hiram Abiff' },
  'history-of-magic-experimental-science': { plate: '/art/ent-history-of-magic-experimental-science.jpg', caption: 'A History of Magic and Experimental Science' },
  'horapollo-hieroglyphica': { plate: '/art/ent-horapollo-hieroglyphica.jpg', caption: 'The Hieroglyphica of Horapollo' },
  hypatia: { plate: '/art/ent-hypatia.jpg', caption: 'Hypatia of Alexandria' },
  'hypnerotomachia-poliphili': { plate: '/art/ent-hypnerotomachia-poliphili.jpg', caption: 'Hypnerotomachia Poliphili' },
  iamblichus: { plate: '/art/ent-iamblichus.jpg', caption: 'Iamblichus' },
  illuminati: { plate: '/art/ent-illuminati.jpg', caption: 'The Bavarian Illuminati' },
  'illustrations-of-masonry': { plate: '/art/ent-illustrations-of-masonry.jpg', caption: 'Illustrations of Masonry' },
  'invisible-college': { plate: '/art/ent-invisible-college.jpg', caption: 'The Invisible College' },
  'isaac-casaubon': { plate: '/art/ent-isaac-casaubon.jpg', caption: 'Isaac Casaubon' },
  'isaac-luria': { plate: '/art/ent-isaac-luria.jpg', caption: 'Isaac Luria' },
  'isaac-newton': { plate: '/art/ent-isaac-newton.jpg', caption: 'Isaac Newton' },
  'isaac-the-blind': { plate: '/art/ent-isaac-the-blind.jpg', caption: 'Isaac the Blind' },
  'israel-regardie': { plate: '/art/ent-israel-regardie.jpg', caption: 'Israel Regardie' },
  'jabir-ibn-hayyan': { plate: '/art/ent-jabir-ibn-hayyan.jpg', caption: 'Jābir ibn Ḥayyān' },
  'jacob-boehme': { plate: '/art/ent-jacob-boehme.jpg', caption: 'Jacob Böhme' },
  'jacob-frank': { plate: '/art/ent-jacob-frank.jpg', caption: 'Jacob Frank' },
  'jan-assmann': { plate: '/art/ent-jan-assmann.jpg', caption: 'Jan Assmann' },
  'jane-lead': { plate: '/art/ent-jane-lead.jpg', caption: 'Jane Lead' },
  'jean-theophile-desaguliers': { plate: '/art/ent-jean-theophile-desaguliers.jpg', caption: 'Jean-Théophile Desaguliers' },
  'jiddu-krishnamurti': { plate: '/art/ent-jiddu-krishnamurti.jpg', caption: 'Jiddu Krishnamurti' },
  'johann-georg-faust': { plate: '/art/ent-johann-georg-faust.jpg', caption: 'Johann Georg Faust' },
  'johann-georg-gichtel': { plate: '/art/ent-johann-georg-gichtel.jpg', caption: 'Johann Georg Gichtel' },
  'johann-valentin-andreae': { plate: '/art/ent-johann-valentin-andreae.jpg', caption: 'Johann Valentin Andreae' },
  'johann-weyer': { plate: '/art/ent-johann-weyer.jpg', caption: 'Johann Weyer' },
  'johannes-bureus': { plate: '/art/ent-johannes-bureus.jpg', caption: 'Johannes Bureus' },
  'johannes-reuchlin': { plate: '/art/ent-johannes-reuchlin.jpg', caption: 'Johannes Reuchlin' },
  'john-dee': { plate: '/art/ent-john-dee.jpg', caption: 'John Dee' },
  'john-heydon': { plate: '/art/ent-john-heydon.jpg', caption: 'John Heydon' },
  'john-pordage': { plate: '/art/ent-john-pordage.jpg', caption: 'John Pordage' },
  'joscelyn-godwin': { plate: '/art/ent-joscelyn-godwin.jpg', caption: 'Joscelyn Godwin' },
  'joseph-dan': { plate: '/art/ent-joseph-dan.jpg', caption: 'Joseph Dan' },
  'joseph-gikatilla': { plate: '/art/ent-joseph-gikatilla.jpg', caption: 'Joseph Gikatilla' },
  'joseph-karo': { plate: '/art/ent-joseph-karo.jpg', caption: 'Joseph Karo' },
  'josephin-peladan': { plate: '/art/ent-josephin-peladan.jpg', caption: 'Joséphin Péladan' },
  kabbalah: { plate: '/art/ent-kabbalah.jpg', caption: 'Kabbalah' },
  'karl-von-hund': { plate: '/art/ent-karl-von-hund.jpg', caption: 'Karl Gotthelf von Hund' },
  'keith-thomas': { plate: '/art/ent-keith-thomas.jpg', caption: 'Keith Thomas' },
  'khalid-ibn-yazid': { plate: '/art/ent-khalid-ibn-yazid.jpg', caption: 'Khālid ibn Yazīd' },
  'kitab-sirr-al-khaliqa': { plate: '/art/ent-kitab-sirr-al-khaliqa.jpg', caption: 'Kitāb Sirr al-Khalīqa' },
  'knorr-von-rosenroth': { plate: '/art/ent-knorr-von-rosenroth.jpg', caption: 'Christian Knorr von Rosenroth' },
  'kore-kosmou': { plate: '/art/ent-kore-kosmou.jpg', caption: 'Korē Kosmou' },
  lactantius: { plate: '/art/ent-lactantius.jpg', caption: 'Lactantius' },
  'laurence-dermott': { plate: '/art/ent-laurence-dermott.jpg', caption: 'Laurence Dermott' },
  'lawrence-principe': { plate: '/art/ent-lawrence-principe.jpg', caption: 'Lawrence M. Principe' },
  'lodovico-lazzarelli': { plate: '/art/ent-lodovico-lazzarelli.jpg', caption: 'Lodovico Lazzarelli' },
  london: { plate: '/art/ent-london.jpg', caption: 'London' },
  'louis-claude-de-saint-martin': { plate: '/art/ent-louis-claude-de-saint-martin.jpg', caption: 'Louis-Claude de Saint-Martin' },
  'lynn-thorndike': { plate: '/art/ent-lynn-thorndike.jpg', caption: 'Lynn Thorndike' },
  'macgregor-mathers': { plate: '/art/ent-macgregor-mathers.jpg', caption: 'S. L. MacGregor Mathers' },
  'macrocosm-microcosm': { plate: '/art/ent-macrocosm-microcosm.jpg', caption: 'Macrocosm and Microcosm' },
  'magia-naturalis': { plate: '/art/ent-magia-naturalis.jpg', caption: 'Magia Naturalis' },
  'magic-flute': { plate: '/art/ent-magic-flute.jpg', caption: 'The Magic Flute' },
  'magnum-opus': { plate: '/art/ent-magnum-opus.jpg', caption: 'The Magnum Opus' },
  'margaret-jacob': { plate: '/art/ent-margaret-jacob.jpg', caption: 'Margaret C. Jacob' },
  'margaret-murray': { plate: '/art/ent-margaret-murray.jpg', caption: 'Margaret Murray' },
  'maria-hebraea': { plate: '/art/ent-maria-hebraea.jpg', caption: 'Maria the Jewess' },
  'marsilio-ficino': { plate: '/art/ent-marsilio-ficino.jpg', caption: 'Marsilio Ficino' },
  'martinez-de-pasqually': { plate: '/art/ent-martinez-de-pasqually.jpg', caption: 'Martinez de Pasqually' },
  'martinist-order': { plate: '/art/ent-martinist-order.jpg', caption: 'The Martinist Order' },
  'masonic-apron': { plate: '/art/ent-masonic-apron.jpg', caption: 'The Masonic Apron' },
  'merkabah-mysticism': { plate: '/art/ent-merkabah-mysticism.jpg', caption: 'Merkabah Mysticism' },
  'michael-maier': { plate: '/art/ent-michael-maier.jpg', caption: 'Michael Maier' },
  'michael-sendivogius': { plate: '/art/ent-michael-sendivogius.jpg', caption: 'Michael Sendivogius' },
  'mircea-eliade': { plate: '/art/ent-mircea-eliade.jpg', caption: 'Mircea Eliade' },
  mnemohistory: { plate: '/art/ent-mnemohistory.jpg', caption: 'Mnemohistory' },
  'monas-hieroglyphica': { plate: '/art/ent-monas-hieroglyphica.jpg', caption: 'Monas Hieroglyphica' },
  'morgan-affair': { plate: '/art/ent-morgan-affair.jpg', caption: 'The Morgan Affair' },
  'moses-de-leon': { plate: '/art/ent-moses-de-leon.jpg', caption: 'Moses de León' },
  'moshe-hayyim-luzzatto': { plate: '/art/ent-moshe-hayyim-luzzatto.jpg', caption: 'Moshe Hayyim Luzzatto' },
  mozart: { plate: '/art/ent-mozart.jpg', caption: 'Wolfgang Amadeus Mozart' },
  'mutus-liber': { plate: '/art/ent-mutus-liber.jpg', caption: 'Mutus Liber' },
  'mystical-qabalah': { plate: '/art/ent-mystical-qabalah.jpg', caption: 'The Mystical Qabalah' },
  'nag-hammadi-library': { plate: '/art/ent-nag-hammadi-library.jpg', caption: 'The Nag Hammadi Discovery' },
  nahmanides: { plate: '/art/ent-nahmanides.jpg', caption: 'Nahmanides' },
  'nathan-of-gaza': { plate: '/art/ent-nathan-of-gaza.jpg', caption: 'Nathan of Gaza' },
  'natural-magic': { plate: '/art/ent-natural-magic.jpg', caption: 'Natural Magic' },
  neoplatonism: { plate: '/art/ent-neoplatonism.jpg', caption: 'Neoplatonism' },
  'nicholas-goodrick-clarke': { plate: '/art/ent-nicholas-goodrick-clarke.jpg', caption: 'Nicholas Goodrick-Clarke' },
  'nicolas-flamel': { plate: '/art/ent-nicolas-flamel.jpg', caption: 'Nicolas Flamel' },
  'nine-hundred-theses': { plate: '/art/ent-nine-hundred-theses.jpg', caption: 'The 900 Theses' },
  'novum-lumen-chymicum': { plate: '/art/ent-novum-lumen-chymicum.jpg', caption: 'Novum Lumen Chymicum' },
  'occult-philosophy-elizabethan': { plate: '/art/ent-occult-philosophy-elizabethan.jpg', caption: 'The Occult Philosophy in the Elizabethan Age' },
  'occult-revival-movement': { plate: '/art/ent-occult-revival-movement.jpg', caption: 'The Occult Revival' },
  'old-charges': { plate: '/art/ent-old-charges.jpg', caption: 'The Old Charges' },
  'ordo-templi-orientis': { plate: '/art/ent-ordo-templi-orientis.jpg', caption: 'Ordo Templi Orientis' },
  ouroboros: { plate: '/art/ent-ouroboros.jpg', caption: 'Ouroboros' },
  'owen-davies': { plate: '/art/ent-owen-davies.jpg', caption: 'Owen Davies' },
  'p-d-ouspensky': { plate: '/art/ent-p-d-ouspensky.jpg', caption: 'P. D. Ouspensky' },
  'pamela-colman-smith': { plate: '/art/ent-pamela-colman-smith.jpg', caption: 'Pamela Colman Smith' },
  pansophia: { plate: '/art/ent-pansophia.jpg', caption: 'Pansophia' },
  'papal-bull-1738': { plate: '/art/ent-papal-bull-1738.jpg', caption: 'In Eminenti' },
  papus: { plate: '/art/ent-papus.jpg', caption: 'Papus' },
  paracelsus: { plate: '/art/ent-paracelsus.jpg', caption: 'Paracelsus' },
  'pardes-rimmonim': { plate: '/art/ent-pardes-rimmonim.jpg', caption: 'Pardes Rimmonim' },
  pentagram: { plate: '/art/ent-pentagram.jpg', caption: 'The Pentagram' },
  'perennial-philosophy': { plate: '/art/ent-perennial-philosophy.jpg', caption: 'The Perennial Philosophy' },
  'philadelphian-society': { plate: '/art/ent-philadelphian-society.jpg', caption: 'The Philadelphian Society' },
  'philosophers-stone': { plate: '/art/ent-philosophers-stone.jpg', caption: 'The Philosophers’ Stone' },
  picatrix: { plate: '/art/ent-picatrix.jpg', caption: 'Picatrix (Ghāyat al-Ḥakīm)' },
  'pico-condemnation': { plate: '/art/ent-pico-condemnation.jpg', caption: 'The Condemnation of Pico’s Theses' },
  'pico-della-mirandola': { plate: '/art/ent-pico-della-mirandola.jpg', caption: 'Giovanni Pico della Mirandola' },
  plotinus: { plate: '/art/ent-plotinus.jpg', caption: 'Plotinus' },
  poimandres: { plate: '/art/ent-poimandres.jpg', caption: 'Poimandres' },
  porphyry: { plate: '/art/ent-porphyry.jpg', caption: 'Porphyry of Tyre' },
  'prima-materia': { plate: '/art/ent-prima-materia.jpg', caption: 'Prima Materia' },
  'prince-hall-freemasonry': { plate: '/art/ent-prince-hall-freemasonry.jpg', caption: 'Prince Hall Freemasonry' },
  'prince-hall': { plate: '/art/ent-prince-hall.jpg', caption: 'Prince Hall' },
  'prisca-theologia': { plate: '/art/ent-prisca-theologia.jpg', caption: 'Prisca Theologia' },
  proclus: { plate: '/art/ent-proclus.jpg', caption: 'Proclus' },
  'pseudo-geber': { plate: '/art/ent-pseudo-geber.jpg', caption: 'Pseudo-Geber' },
  'pseudo-llull': { plate: '/art/ent-pseudo-llull.jpg', caption: 'Pseudo-Lull' },
  'psychology-and-alchemy': { plate: '/art/ent-psychology-and-alchemy.jpg', caption: 'Psychology and Alchemy' },
  'quirinus-kuhlmann': { plate: '/art/ent-quirinus-kuhlmann.jpg', caption: 'Quirinus Kuhlmann' },
  'ramsays-oration': { plate: '/art/ent-ramsays-oration.jpg', caption: 'Ramsay’s Oration' },
  'reginald-scot': { plate: '/art/ent-reginald-scot.jpg', caption: 'Reginald Scot' },
  'rejected-knowledge': { plate: '/art/ent-rejected-knowledge.jpg', caption: 'Rejected Knowledge' },
  religionism: { plate: '/art/ent-religionism.jpg', caption: 'Religionism' },
  'renaissance-magic': { plate: '/art/ent-renaissance-magic.jpg', caption: 'Renaissance Magic' },
  'rider-waite-smith-tarot': { plate: '/art/ent-rider-waite-smith-tarot.jpg', caption: 'The Rider–Waite–Smith Tarot' },
  'ripley-scroll': { plate: '/art/ent-ripley-scroll.jpg', caption: 'The Ripley Scroll' },
  'ritman-library': { plate: '/art/ent-ritman-library.jpg', caption: 'The Ritman Library (BPH)' },
  'robert-boyle': { plate: '/art/ent-robert-boyle.jpg', caption: 'Robert Boyle' },
  'robert-fludd': { plate: '/art/ent-robert-fludd.jpg', caption: 'Robert Fludd' },
  'roger-bacon': { plate: '/art/ent-roger-bacon.jpg', caption: 'Roger Bacon' },
  'ronald-hutton': { plate: '/art/ent-ronald-hutton.jpg', caption: 'Ronald Hutton' },
  'rosarium-philosophorum': { plate: '/art/ent-rosarium-philosophorum.jpg', caption: 'Rosarium Philosophorum' },
  'rose-cross': { plate: '/art/ent-rose-cross.jpg', caption: 'The Rose Cross' },
  'rosicrucian-furore': { plate: '/art/ent-rosicrucian-furore.jpg', caption: 'The Rosicrucian Furore' },
  rosicrucianism: { plate: '/art/ent-rosicrucianism.jpg', caption: 'Rosicrucianism' },
  'royal-arch': { plate: '/art/ent-royal-arch.jpg', caption: 'The Royal Arch' },
  'rudolf-ii': { plate: '/art/ent-rudolf-ii.jpg', caption: 'Rudolf II' },
  'rudolf-steiner': { plate: '/art/ent-rudolf-steiner.jpg', caption: 'Rudolf Steiner' },
  'sabians-of-harran': { plate: '/art/ent-sabians-of-harran.jpg', caption: 'The Sabians of Harran' },
  safed: { plate: '/art/ent-safed.jpg', caption: 'Safed' },
  'salon-rose-croix': { plate: '/art/ent-salon-rose-croix.jpg', caption: 'The Salon de la Rose+Croix' },
  'samuel-hartlib': { plate: '/art/ent-samuel-hartlib.jpg', caption: 'Samuel Hartlib' },
  'sceptical-chymist': { plate: '/art/ent-sceptical-chymist.jpg', caption: 'The Sceptical Chymist' },
  'schaw-statutes': { plate: '/art/ent-schaw-statutes.jpg', caption: 'The Schaw Statutes' },
  'scottish-rite': { plate: '/art/ent-scottish-rite.jpg', caption: 'The Scottish Rite' },
  'secret-doctrine': { plate: '/art/ent-secret-doctrine.jpg', caption: 'The Secret Doctrine' },
  'secrets-of-alchemy': { plate: '/art/ent-secrets-of-alchemy.jpg', caption: 'The Secrets of Alchemy' },
  'sefer-ha-bahir': { plate: '/art/ent-sefer-ha-bahir.jpg', caption: 'Sefer ha-Bahir' },
  'sefer-raziel': { plate: '/art/ent-sefer-raziel.jpg', caption: 'Sefer Raziel ha-Malakh' },
  'sefer-yetzirah': { plate: '/art/ent-sefer-yetzirah.jpg', caption: 'Sefer Yetzirah' },
  sefirot: { plate: '/art/ent-sefirot.jpg', caption: 'The Sefirot' },
  'shabbetai-tzvi': { plate: '/art/ent-shabbetai-tzvi.jpg', caption: 'Shabbetai Tzvi' },
  shekhinah: { plate: '/art/ent-shekhinah.jpg', caption: 'The Shekhinah' },
  'shevirat-ha-kelim': { plate: '/art/ent-shevirat-ha-kelim.jpg', caption: 'Shevirat ha-Kelim' },
  sigil: { plate: '/art/ent-sigil.jpg', caption: 'The Sigil' },
  'signatura-rerum': { plate: '/art/ent-signatura-rerum.jpg', caption: 'De Signatura Rerum' },
  'society-psychical-research': { plate: '/art/ent-society-psychical-research.jpg', caption: 'The Society for Psychical Research' },
  'solomon-alkabetz': { plate: '/art/ent-solomon-alkabetz.jpg', caption: 'Solomon Alkabetz' },
  'speculative-masonry': { plate: '/art/ent-speculative-masonry.jpg', caption: 'Speculative Masonry' },
  spiritism: { plate: '/art/ent-spiritism.jpg', caption: 'Spiritism' },
  'spiritual-and-demonic-magic': { plate: '/art/ent-spiritual-and-demonic-magic.jpg', caption: 'Spiritual and Demonic Magic from Ficino to Campanella' },
  spiritualism: { plate: '/art/ent-spiritualism.jpg', caption: 'Spiritualism' },
  'splendor-solis': { plate: '/art/ent-splendor-solis.jpg', caption: 'Splendor Solis' },
  'square-and-compasses': { plate: '/art/ent-square-and-compasses.jpg', caption: 'The Square and Compasses' },
  steganographia: { plate: '/art/ent-steganographia.jpg', caption: 'Steganographia' },
  'stobaean-hermetica': { plate: '/art/ent-stobaean-hermetica.jpg', caption: 'The Stobaean Hermetica' },
  'strict-observance': { plate: '/art/ent-strict-observance.jpg', caption: 'The Rite of Strict Observance' },
  'summa-perfectionis': { plate: '/art/ent-summa-perfectionis.jpg', caption: 'Summa Perfectionis' },
  synesius: { plate: '/art/ent-synesius.jpg', caption: 'Synesius of Cyrene' },
  talisman: { plate: '/art/ent-talisman.jpg', caption: 'The Talisman' },
  'tarot-des-bohemiens': { plate: '/art/ent-tarot-des-bohemiens.jpg', caption: 'Le Tarot des Bohémiens' },
  tarot: { plate: '/art/ent-tarot.jpg', caption: 'Tarot' },
  'technical-hermetica': { plate: '/art/ent-technical-hermetica.jpg', caption: 'The Technical Hermetica' },
  'temple-of-solomon': { plate: '/art/ent-temple-of-solomon.jpg', caption: 'The Temple of Solomon' },
  'the-fourth-way': { plate: '/art/ent-the-fourth-way.jpg', caption: 'The Fourth Way' },
  'theatrum-chemicum-britannicum': { plate: '/art/ent-theatrum-chemicum-britannicum.jpg', caption: 'Theatrum Chemicum Britannicum' },
  thelema: { plate: '/art/ent-thelema.jpg', caption: 'Thelema' },
  'theosophical-society': { plate: '/art/ent-theosophical-society.jpg', caption: 'The Theosophical Society' },
  theurgy: { plate: '/art/ent-theurgy.jpg', caption: 'Theurgy' },
  'thomas-norton': { plate: '/art/ent-thomas-norton.jpg', caption: 'Thomas Norton' },
  'thomas-vaughan': { plate: '/art/ent-thomas-vaughan.jpg', caption: 'Thomas Vaughan' },
  thoth: { plate: '/art/ent-thoth.jpg', caption: 'Thoth' },
  'three-books-of-occult-philosophy': { plate: '/art/ent-three-books-of-occult-philosophy.jpg', caption: 'Three Books of Occult Philosophy' },
  tikkun: { plate: '/art/ent-tikkun.jpg', caption: 'Tikkun' },
  'tommaso-campanella': { plate: '/art/ent-tommaso-campanella.jpg', caption: 'Tommaso Campanella' },
  'tracing-board': { plate: '/art/ent-tracing-board.jpg', caption: 'The Tracing Board' },
  'tree-of-life': { plate: '/art/ent-tree-of-life.jpg', caption: 'The Tree of Life' },
  'tria-prima': { plate: '/art/ent-tria-prima.jpg', caption: 'The Tria Prima' },
  trithemius: { plate: '/art/ent-trithemius.jpg', caption: 'Johannes Trithemius' },
  'triumphal-chariot-antimony': { plate: '/art/ent-triumphal-chariot-antimony.jpg', caption: 'The Triumphal Chariot of Antimony' },
  'tubingen-circle': { plate: '/art/ent-tubingen-circle.jpg', caption: 'The Tübingen Circle' },
  'turba-philosophorum': { plate: '/art/ent-turba-philosophorum.jpg', caption: 'Turba Philosophorum' },
  tzimtzum: { plate: '/art/ent-tzimtzum.jpg', caption: 'Tzimtzum' },
  'united-grand-lodge': { plate: '/art/ent-united-grand-lodge.jpg', caption: 'The United Grand Lodge of England' },
  'utriusque-cosmi-historia': { plate: '/art/ent-utriusque-cosmi-historia.jpg', caption: 'Utriusque Cosmi Historia' },
  'van-helmont': { plate: '/art/ent-van-helmont.jpg', caption: 'Jan Baptist van Helmont' },
  'voynich-manuscript': { plate: '/art/ent-voynich-manuscript.jpg', caption: 'The Voynich Manuscript' },
  'warburg-institute': { plate: '/art/ent-warburg-institute.jpg', caption: 'The Warburg Institute' },
  'wb-yeats': { plate: '/art/ent-wb-yeats.jpg', caption: 'W. B. Yeats' },
  'western-esoteric-traditions-book': { plate: '/art/ent-western-esoteric-traditions-book.jpg', caption: 'The Western Esoteric Traditions' },
  'western-esotericism-field': { plate: '/art/ent-western-esotericism-field.jpg', caption: 'The Academic Study of Western Esotericism' },
  'white-mountain': { plate: '/art/ent-white-mountain.jpg', caption: 'The Battle of White Mountain' },
  wicca: { plate: '/art/ent-wicca.jpg', caption: 'Wicca' },
  'william-law': { plate: '/art/ent-william-law.jpg', caption: 'William Law' },
  'william-newman': { plate: '/art/ent-william-newman.jpg', caption: 'William R. Newman' },
  'william-preston': { plate: '/art/ent-william-preston.jpg', caption: 'William Preston' },
  'william-schaw': { plate: '/art/ent-william-schaw.jpg', caption: 'William Schaw' },
  'william-wynn-westcott': { plate: '/art/ent-william-wynn-westcott.jpg', caption: 'William Wynn Westcott' },
  'wouter-hanegraaff': { plate: '/art/ent-wouter-hanegraaff.jpg', caption: 'Wouter Hanegraaff' },
  'yates-thesis': { plate: '/art/ent-yates-thesis.jpg', caption: 'The Yates Thesis' },
  zohar: { plate: '/art/ent-zohar.jpg', caption: 'The Zohar' },
  zosimos: { plate: '/art/ent-zosimos.jpg', caption: 'Zosimos of Panopolis' },
};
